#! /bin/sh
### BEGIN INIT INFO
# Provides:  monitor
# Required-Start: $all	
# Required-Stop:  	 
# Default-Start:	 2 3 4 5
# Default-Stop:	  0 1 6
# Short-Description: Start Monitor  Server
# Description:	   Start Monitor  Server 
### END INIT INFO


PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=monitor
DIR=/opt/monitor/
SETTINGS=/etc/monitor/
DAEMON=/opt/monitor/monitor.py
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/monitor.start.log
PYTHONPATH=$PYTHONPATH:/opt/monitor/
export PYTHONPATH

case "$1" in
  start)
	echo -n "Starting Main Program: "
        echo $(date) $NAME  "started"  >> $LOGFILE
	$DAEMON $SETTINGS  &
	echo $! > $PIDFILE
	echo "done."
	;;
  stop)
	echo -n "Stopping program: "
	echo $(date) $NAME "program stopped" >> $LOGFILE
	PID=$(cat $PIDFILE)
	kill -9 $PID
	echo "done."
	;;
  status)
        status_of_proc "$NAME" "$DAEMON" && exit 0 || exit $?
        ;;

  *)
	echo "Usage: /etc/init.d/monitor {start|stop}"
	exit 1
	;;
esac
exit 0
