#! /bin/sh
### BEGIN INIT INFO
# Provides:  monitor
# Required-Start: $all	
# Required-Stop:  	 
# Default-Start:	 2 3 4 5
# Default-Stop:	  0 1 6
# Short-Description:  Monitor  Server
# Description:	    Monitor  Server 
### END INIT INFO


PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=monitor
DIR=/opt/monitor/
DAEMON_ARGS="/etc/monitor/settings.yaml --log=DEBUG"
DAEMON=/opt/monitor/monitor.py
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/monitor.log
PYTHONPATH=$PYTHONPATH:/opt/monitor/
export PYTHONPATH

case "$1" in
  start)
	echo -n "Starting program: " $NAME
       start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --background --startas $DAEMON --no-close  -- $DAEMON_ARGS 
	;;
  stop)
        echo -n "Stopping daemon: "$NAME
	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        echo "."
	;;

 restart)
        echo -n "Restarting daemon: "$NAME
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
       start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --background --startas $DAEMON --no-close  -- $DAEMON_ARGS 
        ;;
 status)
        status_of_proc "$NAME" "$DAEMON" && exit 0 || exit $?
        ;;


  *)
	echo "Usage: /etc/init.d/monitor {start|stop}"
	exit 1
	;;
esac
exit 0
